export const paths = {
  home: '/',
  auth: { signIn: '/auth/sign-in', signUp: '/auth/sign-up', resetPassword: '/auth/reset-password' },
  dashboard: {
    overview: '/dashboard',
    AiAgent: '/dashboard',
    Claude: '/dashboard/claude',
    CAP: '/dashboard/cap',
    Deepfake: '/dashboard/deepfake',
    ImageGenerator: '/dashboard/image-generator',
    ListAgents: '/dashboard/list-agents',
    QuizGenerator: '/dashboard/quiz-generator',
    QuoteImageGenerator: '/dashboard/quote-image-generator',
    StatisticalDataAnalyzer: '/dashboard/statistical-data-analyzer',
    StoryTellingApp: '/dashboard/story-telling-app',
    ToDoAssistant: '/dashboard/todo-assistant',
    account: '/dashboard/account',
    settings: '/dashboard/settings',
  },
  errors: { notFound: '/errors/not-found' },
} as const;
